.idea/misc.xml, app/src/main/java/com/acpc/mobilepatienttracker/DatabaseManager.java
Testing merging of blank classes bc i dont what im doing
=> Initial commit

app/src/main/AndroidManifest.xml, app/src/main/java/com/acpc/mobilepatienttracker/LoginPatient.java, app/src/main/java/com/acpc/mobilepatienttracker/MainActivity.java, app/src/main/java/com/acpc/mobilepatienttracker/SplashActivity.java, app/src/main/res/layout/acitivity_login.xml, app/src/main/res/layout/activity_main.xml, build.gradle, gradle/wrapper/gradle-wrapper.properties
Merged Wiehann's Patient Login page
=> Login patient

app/build.gradle, app/src/main/java/com/acpc/mobilepatienttracker/DHomePage.java, app/src/main/java/com/acpc/mobilepatienttracker/DPatientDetails.java, app/src/main/java/com/acpc/mobilepatienttracker/MainActivity.java, app/src/main/java/com/acpc/mobilepatienttracker/PatientListAdapter.java, app/src/main/res/drawable/border_set_patient_list.xml, app/src/main/res/layout/activity_d_home_page.xml, app/src/main/res/layout/activity_d_patient_details.xml, app/src/main/res/layout/doc_list_item.xml
The list was implemented through the a RecycleViewer and Adapter added to the home page of the Doctor
=> Added feature for Doctor's to be able to view a list of patients.

app/src/main/AndroidManifest.xml, app/src/main/java/com/acpc/mobilepatienttracker/MainActivity.java, app/src/main/java/com/acpc/mobilepatienttracker/PHomePage.java, app/src/main/java/com/acpc/mobilepatienttracker/PUpdateField.java, app/src/main/java/com/acpc/mobilepatienttracker/PatientDetails.java, app/src/main/res/color/detailview_color.xml, app/src/main/res/drawable/ic_baseline_cancel_24.xml, app/src/main/res/drawable/ic_baseline_edit_24.xml, app/src/main/res/drawable/ic_baseline_save_24.xml, app/src/main/res/layout/activity_p_home_page.xml, app/src/main/res/layout/activity_p_update_field.xml, app/src/main/res/layout/activity_patient_details.xml
Added functionality to update each entry to the database (a better way may be added later)
=> Reworked PatientDetails activity

app/src/main/AndroidManifest.xml, app/src/main/java/com/acpc/mobilepatienttracker/DHomePage.java, app/src/main/java/com/acpc/mobilepatienttracker/LoginDoctor.java, app/src/main/java/com/acpc/mobilepatienttracker/PHomePage.java, app/src/main/java/com/acpc/mobilepatienttracker/PatientBookings.java, app/src/main/java/com/acpc/mobilepatienttracker/PatientConsultationHistory.java, app/src/main/java/com/acpc/mobilepatienttracker/PatientDetails.java, app/src/main/res/layout/activity_d_home_page.xml, app/src/main/res/layout/activity_d_registration.xml, app/src/main/res/layout/activity_p_home_page.xml, app/src/main/res/layout/activity_p_registration.xml, app/src/main/res/layout/activity_patient_consultation_history.xml, app/src/main/res/layout/activity_patient_details.xml, app/src/main/res/menu/p_menu_navigation.xml
Changed headings of screens, added logout button for doctor and fixed the navigation bar items etc.
=> General UI fixes and logout button for doctor added.

.idea/.name, app/src/main/java/com/acpc/mobilepatienttracker/DHomePage.java, app/src/main/java/com/acpc/mobilepatienttracker/DoctorConsultForm.java, app/src/main/java/com/acpc/mobilepatienttracker/MainActivity.java, app/src/main/res/layout/activity_d_home_page.xml, app/src/main/res/layout/activity_doctor_consult_form.xml, app/src/main/res/values/ids.xml
Data can be added to DB from Consultation Form
=> Consultation form

app/src/main/java/com/acpc/mobilepatienttracker/DRegistration.java, app/src/main/java/com/acpc/mobilepatienttracker/PRegistration.java
Privacy policy working for patient and doctor
=> fixing privacy policy update

app/src/main/AndroidManifest.xml, app/src/main/java/com/acpc/mobilepatienttracker/DocTypeAdapter.java, app/src/main/java/com/acpc/mobilepatienttracker/DocTypeList.java, app/src/main/java/com/acpc/mobilepatienttracker/MainActivity.java, app/src/main/java/com/acpc/mobilepatienttracker/PatientBookings.java, app/src/main/res/layout/activity_doc_type_list.xml, app/src/main/res/layout/activity_patient_bookings.xml, app/src/main/res/layout/doc_type_list_item.xml
=> Keanu's Code - (With fragment update)

app/src/main/java/com/acpc/mobilepatienttracker/DBookingDetails.java, app/src/main/java/com/acpc/mobilepatienttracker/DHomePage.java, app/src/main/java/com/acpc/mobilepatienttracker/DoctorDetails.java, app/src/main/java/com/acpc/mobilepatienttracker/DoctorFragActivity.java, app/src/main/java/com/acpc/mobilepatienttracker/DoctorPatientList.java, app/src/main/java/com/acpc/mobilepatienttracker/PHomePage.java, app/src/main/java/com/acpc/mobilepatienttracker/PatientBookings.java, app/src/main/java/com/acpc/mobilepatienttracker/PatientDetails.java, app/src/main/java/com/acpc/mobilepatienttracker/PatientFragActivity.java, app/src/main/java/com/acpc/mobilepatienttracker/PendingBookings.java, app/src/main/res/layout/activity_d_home_page.xml
UI changes and Accept/Reject button changes.
=> Small UI changes added.

app/src/main/java/com/acpc/mobilepatienttracker/DHomePage.java, app/src/main/java/com/acpc/mobilepatienttracker/DPatientDetails.java, app/src/main/java/com/acpc/mobilepatienttracker/DoctorFragActivity.java, app/src/main/java/com/acpc/mobilepatienttracker/PHomePage.java, app/src/main/java/com/acpc/mobilepatienttracker/PatientFragActivity.java, app/src/main/res/drawable/ic_baseline_login_24.xml, app/src/main/res/drawable/ic_baseline_post_add_24.xml, app/src/main/res/layout/activity_d_home_page.xml, app/src/main/res/layout/activity_p_home_page.xml, app/src/main/res/menu/log_consult.xml, app/src/main/res/menu/log_menu.xml
Updated Consult Form Button Placement to title bar for DPatientDetails
=> Updated Logout Button Placement to title bar for all home screens

.idea/misc.xml, app/build.gradle, app/src/main/java/com/acpc/mobilepatienttracker/DHomePage.java, app/src/main/java/com/acpc/mobilepatienttracker/PHomePage.java, app/src/main/res/layout/activity_d_home_page.xml
Patient and Doctor calendar working
=> Patient doctor calendar

app/src/main/java/com/acpc/mobilepatienttracker/DHomePage.java, app/src/main/java/com/acpc/mobilepatienttracker/Group.java, app/src/main/java/com/acpc/mobilepatienttracker/PHomePage.java, app/src/main/java/com/acpc/mobilepatienttracker/PHomepageAdapter.java, app/src/main/res/layout/activity_d_home_page.xml, app/src/main/res/layout/activity_p_home_page.xml, app/src/main/res/layout/listrow_details.xml, app/src/main/res/layout/listrow_group.xml
Added in Expandable list for calendar for doctors and patients
=> ******CHANGELOG*********

.idea/.name, .idea/compiler.xml, .idea/misc.xml, .idea/runConfigurations.xml, app/src/main/java/com/acpc/mobilepatienttracker/DoctorConsultationList.java, app/src/test/java/com/acpc/mobilepatienttracker/DoctorConsultationListTest.java
Unit test done for DoctorConsultationList
=> Unit Test for DoctorConsultationList is done.

.idea/.name, app/src/main/java/com/acpc/mobilepatienttracker/DPatientDetails.java, app/src/main/java/com/acpc/mobilepatienttracker/DoctorConsultForm.java
Uses bundles and not public variables
=> DocConsultForm now uses bundles and not public vars

.idea/compiler.xml, .idea/misc.xml, .idea/runConfigurations.xml, app/src/main/java/com/acpc/mobilepatienttracker/DHomePage.java, app/src/main/java/com/acpc/mobilepatienttracker/DHomePageAdapter.java, app/src/main/res/drawable/ic_baseline_add_24.xml, app/src/main/res/layout/activity_d_home_page.xml
Button to create consult form works. Needs to be linked with specific bookings now.
=> Added button to create consult form.

.idea/.name, app/src/main/java/com/acpc/mobilepatienttracker/DHomePage.java, app/src/main/java/com/acpc/mobilepatienttracker/DHomePageAdapter.java, app/src/main/java/com/acpc/mobilepatienttracker/DoctorConsultForm.java, app/src/main/java/com/acpc/mobilepatienttracker/FirebasePatient.java, app/src/main/java/com/acpc/mobilepatienttracker/PHomePage.java, app/src/main/java/com/acpc/mobilepatienttracker/PHomepageAdapter.java, app/src/main/res/layout/activity_doctor_consult_form.xml, app/src/main/res/layout/listrow_details.xml
Doctor can now go to consult form from calendar.
=> Clickable events

app/src/main/java/com/acpc/mobilepatienttracker/ConsultationDetails.java, app/src/main/res/layout/activity_consultation_details.xml, app/src/test/java/com/acpc/mobilepatienttracker/ConsultationHistoryAdapterTest.java
=> Fixed some accepted bookings not showing up in calender

app/src/main/java/com/acpc/mobilepatienttracker/DHomePage.java, app/src/main/java/com/acpc/mobilepatienttracker/PHomePage.java
=> this should have been merged

app/src/main/res/layout/acitivity_plogin.xml, app/src/main/res/layout/activity_doctor_or_patientt.xml, app/src/main/res/layout/activity_login_doctor.xml
Changed to round buttons in Doctor or Patient
=> Fixed Doctor and Patient login XML files

.idea/.name, .idea/compiler.xml, .idea/misc.xml, .idea/runConfigurations.xml, app/src/main/java/com/acpc/mobilepatienttracker/ConsultationDetails.java, app/src/main/java/com/acpc/mobilepatienttracker/DHomePage.java, app/src/main/java/com/acpc/mobilepatienttracker/DoctorDetails.java, app/src/main/java/com/acpc/mobilepatienttracker/MainActivity.java, app/src/main/java/com/acpc/mobilepatienttracker/PHomePage.java, app/src/main/java/com/acpc/mobilepatienttracker/PatientDetails.java, app/src/main/res/drawable/dialog_background.xml, app/src/main/res/layout/custom_dialog.xml, app/src/main/res/values/colors.xml
Loading dialog added to correct places.
=> Final loading dialog

app/src/main/java/com/acpc/mobilepatienttracker/DoctorDetails.java, app/src/main/java/com/acpc/mobilepatienttracker/PatientDetails.java, app/src/main/res/drawable/ic_baseline_edit_24.xml, app/src/main/res/layout/activity_doctor_details.xml, app/src/main/res/layout/activity_patient_details.xml
Changed Icon and text colour for user details
Added surname field to user details
=> ------CHANGES--------
